export const authConstants = {
    LOGINREQUEST: "LOGINREQUEST",
    LOGINFAILURE: "LOGINFAILURE",
    LOGINSUCCESS: "LOGINSUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const categoryConstants = {
    GET_AL_CATEGORIES_REQUEST: "GET_AL_CATEGORIES_REQUEST",
    GET_AL_CATEGORIES_SUCCESS: "GET_AL_CATEGORIES_SUCCESS",
    GET_AL_CATEGORIES_FAILURE: "GET_AL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE"
}