export const authConstants = {
    LOGINREQUEST: "LOGINREQUEST",
    LOGINFAILURE: "LOGINFAILURE",
    LOGINSUCCESS: "LOGINSUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}